version: '3'
services:
    webide:
        image: "${WEBIDE_IMAGE}"
        environment:
            - DATA_DIR=/tmp
        volumes:
            - /tmp:/tmp
        logging:
            driver: none
    e2e:
        build: .
        environment:
            - API_HOST=http://webide:8080
        volumes:
            - /tmp:/tmp
        depends_on:
            - webide
